version: '2'
services:
    maferme-app:
        image: maferme
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://maferme-mysql:3306/maferme?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=maferme-elasticsearch:9300
        ports:
            - 8080:8080
    maferme-mysql:
        extends:
            file: mysql.yml
            service: maferme-mysql
    maferme-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: maferme-elasticsearch
